### ISSUE TITLE
Lacking of proper reference GTFs

### ISSUE THREAD

**Issue by shengw-c** [mhammell-laboratory/DANCer#1]
Hi there, thank you for providing such a nice framework. After reading your [work](https://www.biorxiv.org/content/10.1101/2024.07.19.603731v1.full), I cannot figure out the reference GTFs you used for the bulk RNA-seq data ("DANcer/datafiles/DANCer_WGCNA_moduleInfo.RData"). I'm now trying to use gencode v35 and GRCh38_Ensembl_rmsk_TE.gtf (provided by TEtranscripts). But seems I'm still missing ~6000 genes. Could you please show more details where I could find the appropriate references? Appreciate it for any advices!

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
For this DANCer model, we are using GENCODE v25 gene annotations, eliminating transcripts where >75% of exon sequences overlap TE. For TE annotations, we are using the TE GTF provided by `TEtranscripts`.

Thanks.

**Comment by shengw-c** [comment]
Thank you Oliver for your quick reply. To be clear, for the TE GTF, do you mean "GRCh38_Ensembl_rmsk_TE.gtf" or "hg38_rmsk_TE.gtf"? 

> For TE annotations, we are using the TE GTF provided by `TEtranscripts`.

Btw, is there any chance you could share the two GTFs in the repository, so that it could be easier for others to use your framework? Thanks again!

**Comment by olivertam** [comment]
Thank you for your suggestions.

I have now added the gene GTF used in the DANCer training. I have also added some information on the TE GTF used.

Thanks.

**Comment by shengw-c** [comment]
This is great! Thank you so much for your prompt responses!
